"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[manager]
    hovered = { fg = "black", bg = "red" }
    preview_hovered = { underline = true }
    
    find_keyword = { fg = "yellow", italic = true }

